//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempConsELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.InstructorAssignments = new HashSet<InstructorAssignment>();
            this.StudentAssignments = new HashSet<StudentAssignment>();
            this.InstructorAssignments1 = new HashSet<InstructorAssignment>();
            this.Lectures = new HashSet<Lecture>();
            this.StudentAssignments1 = new HashSet<StudentAssignment>();
        }
    
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string CourseTitle { get; set; }
        public string CourseDescription { get; set; }
        public string Language { get; set; }
        public Nullable<int> Ratings { get; set; }
        public Nullable<int> NoOfStudentsEnrolled { get; set; }
        public int InstructorId { get; set; }
        public string CourseFieldCategory { get; set; }
        public string CourseCategory { get; set; }
        public string CourseImage { get; set; }
        public string NoOfLectures { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual Course Course2 { get; set; }
        public virtual Instructor Instructor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorAssignment> InstructorAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssignment> StudentAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorAssignment> InstructorAssignments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecture> Lectures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssignment> StudentAssignments1 { get; set; }
    }
}
