//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempConsELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.Courses = new HashSet<Course>();
            this.Courses1 = new HashSet<Course>();
            this.InstructorAssignments = new HashSet<InstructorAssignment>();
            this.InstructorAssignments1 = new HashSet<InstructorAssignment>();
        }
    
        public int InstructorId { get; set; }
        public string InstructorName { get; set; }
        public string Profession { get; set; }
        public Nullable<int> NoOfCoursesTaught { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Reviews { get; set; }
        public Nullable<int> NoOfStudents { get; set; }
        public string About { get; set; }
        public string Degree1 { get; set; }
        public string Degree2 { get; set; }
        public string Degree3 { get; set; }
        public string Image { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorAssignment> InstructorAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructorAssignment> InstructorAssignments1 { get; set; }
    }
}
