//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempConsELearning.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public int LectureId { get; set; }
        public int LectureNo { get; set; }
        public string LectureTitle { get; set; }
        public string LectureDescription { get; set; }
        public int CourseId { get; set; }
        public string VideoTitle { get; set; }
        public string VideoLink { get; set; }
        public string VideoDesription { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Lecture Lecture1 { get; set; }
        public virtual Lecture Lecture2 { get; set; }
    }
}
